name: Health check

#on:
  #schedule:
    #- cron: '0 0 * * *' Commented out so monthly free hours are not consumed.

on:
  push:
    branches:
      - master

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Periodic health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://redux-anecdotes-ci-cd.fly.dev/health-check'